name: publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies and build
        run: npm ci && npx playwright install --with-deps && npm run build

      - name: Run tests
        run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Check for version bump
        id: version_check
        run: |
          git fetch origin main
          BASE=$(git merge-base origin/main HEAD)
          if git diff "$BASE" HEAD -- package.json | grep '"version":'; then
            echo "Version bump detected."
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "No Version bump detected."
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies and build
        if: steps.version_check.outputs.publish == 'true'
        run: npm ci && npm run build

      - name: Publish to npm
        if: steps.version_check.outputs.publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
